// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TOMSU.Emailova_schranka.Infrastructure.Database;

#nullable disable

namespace TOMSU.Emailova_schranka.Infrastructure.Migrations
{
    [DbContext(typeof(EmailDbContext))]
    [Migration("20231210204127_firstMig")]
    partial class firstMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TOMSU.Emailova_schranka.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Odesilatel_Adress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_at = "29.10.2023 17:27:58",
                            Odesilatel_Adress = "nkannkdk@sjajs",
                            Status = "Send",
                            Text = "Blakijdhalhfssjfah",
                            Title = "Title"
                        },
                        new
                        {
                            Id = 2,
                            Created_at = "20.10.2023 17:27:58",
                            Odesilatel_Adress = "nkannkdk@sjajs",
                            Status = "Send",
                            Text = "Blakijdhasadhdjkgadgajgdsgadgjadgjadjglhfssjfah",
                            Title = "Titldadsae"
                        });
                });

            modelBuilder.Entity("TOMSU.Emailova_schranka.Domain.Entities.Odeslani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Prijemce_Adress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Zprava_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Odeslani");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Prijemce_Adress = "nkannkdk@sjajs",
                            Zprava_Id = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
